apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: elated-gecko-java-quarkus 
  janus-idp.io/tekton: elated-gecko-java-quarkus
  backstage.io/kubernetes-id: elated-gecko-java-quarkus
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: elated-gecko-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  